services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - staticfiles:/son/staticfiles
      - ssl_data:/etc/nginx/ssl
    env_file:
      - .env
    ports:
      - 8001:8001
    depends_on:
      - db
    networks:
      - backend

  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    volumes:
      - staticfiles:/son/staticfiles
      - ssl_data:/etc/nginx/ssl
    ports:
      - 8080:8080
    depends_on:
      - web
    networks:
      - backend

  mailservice:
    build: ./mailservice
    env_file:
      - .env
    networks:
      - backend
    hostname: mailservice
    depends_on:
      - web
      - kafka

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    env_file:
      - .env
    networks:
      - kafka-net
      - backend

  kafka:
    container_name: kafka
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    env_file:
      - .env
    networks:
      - kafka-net
      - backend
    restart: unless-stopped

volumes:
  db_data:
  staticfiles:
  ssl_data:


networks:
  backend:
    driver: bridge
  kafka-net:
    driver: bridge
